### PR TITLE
Update cp.php

### PR DESCRIPTION
**Pull request by TimDeJ**
Noticed 'draft' was missing in the translation

### CODE REVIEW

**Comment by jackmcdade** [comment]
Thanks!

**Comment by ebeauchamps** [comment]
I cannot find "draft" in the English cp.php file on line 532.
I am on 2.11.15
Is this added from v3 Alpha?

**Comment by TimDeJ** [comment]
I'm on 2.11.15 as well and there I notices it was missing.

**Comment by ebeauchamps** [comment]
ok, adding this to English and French

**Comment by AndreasSchantl** [comment]
Will do too. Hopefully today and hopefully I don't forget to.

**Pull request merged**
