### PR TITLE
Update grid.php

### PR DESCRIPTION
**Pull request by AndreasSchantl**

### CODE REVIEW

**Comment by jackmcdade** [comment]
I'm not great at german but that looks odd to me. Why is "Reihe-hinzufügen" in quotes?

**Comment by AndreasSchantl** [comment]
To follow correct spelling. It's weird, I know. It is understandable without as well. It's really just about spelling. Most people will not recognize. Do you think it would be better without those?

**Comment by jackmcdade** [comment]
It just looked odd to me, is that a common practice in German? Is there another non-literal translation of "add row" that is more natural? It just needs to mean "create another one of these generic things" in some way and be short and simple.

**Comment by aerni90** [comment]
The right way to say it is `Zeile hinzufügen`. That's the wording Excel uses for `Add row`.

**Comment by jackmcdade** [comment]
Works for me! Want to update the pull request?

**Comment by AndreasSchantl** [comment]
"Zeile hinzufügen" is fine. I have seen that this was a mistake anyways. The quotes are only correct in the instructions. Where is this text even used? I had to double check the English file to see if "Text" is even in there.

**Comment by jackmcdade** [comment]
It's this here, when you're customizing a Grid fieldtype:
image

**Comment by AndreasSchantl** [comment]
Alright, the text fits. If you want to, you can merge. Any other questions regarding the translation as it is right now?

**Comment by jackmcdade** [comment]
Nope! Thank you so much! <3

**Pull request merged**
