### PR TITLE
French CP translation for 2.1.6+ (and English files for Statamic v2)

### PR DESCRIPTION
**Pull request by ebeauchamps**
Those are the French files for Statamic v2. For the v1 version, check out the v1 branch.

If you want to translate or localize the CP in your own language:
With Statamic 2.1.18+
1. put your own language folder xx (short name for your language, 2 letters) in `site/lang/` (after having translated ALL the keys you can find in the files located within the `en` folder)
2. check that users who will access the CP have `locale: xx` in their user.yaml file

With Statamic 2.1.17 and below:
1. in `site/settings/cp.yaml` add `locale: xx` with xx being your own language short string
2. put your own language folder xx in `site/lang/` (after having translated ALL the keys you can find in the files located within the `en` folder)
3. check that users who will access the CP have `locale: xx` in their user.yaml file

### CODE REVIEW

**Comment by ebeauchamps** [comment]
Looking nice now with 2.1.18! Thanks to The Gentlemen!

**Comment by SuperKiwi** [comment]
Any idea with this PR has not been accepted ?

**Comment by jackmcdade** [comment]
Because it doesn't belong on this branch. We need to set up a v2 branch.

**Comment by ebeauchamps** [comment]
Sorry Jack, but there is a v1 branch and a master branch and this PR is on the master branch not on the v1.

There wasn't any v2 branch when I started to work on it.

**Comment by pelletiermaxime** [comment]
Am I missing something ? Are all the translations in this repo for Statamic 1 ?
Anyway, thanks for the french translations!

**Comment by ebeauchamps** [comment]
Maxime


Les traductions pour Statamic 1 sont dans la branche v1 et la branche Master puisse que toutes mes PR sont restées en attente pour la v2


Si tu fork mon repo, tu auras accès aux traductions à jour pour la V2


Cdt,


Emmanuel


________________________________
De : Maxime Pelletier <notifications@github.com>
Envoyé : jeudi 29 juin 2017 01:38
À : statamic/i18n
Cc : Emmanuel Beauchamps; Author
Objet : Re: [statamic/i18n] French CP translation for 2.1.6+ (and English files for Statamic v2) (#64)


Am I missing something ? Are all the translations in this repo for Statamic 1 ?
Anyway, thanks for the french translations!

**Comment by pelletiermaxime** [comment]
Yeah I know, that's how I used them. I was just wondering why there wasn't a V2 branch yet. Localizing the CP seems like an important feature to have and it probably should work by default.

**Pull request merged**
