### PR TITLE
upgrade russian lang for support v2.11.12

### PR DESCRIPTION
**Pull request by v0ff4k**
no real tests, just comparing to english, and translate missed parts

### CODE REVIEW

**Comment by v0ff4k** [comment]
@jackmcdade  is ok with my pull request ?  im not every day puller but i think its "ok" pull request.

**Comment by jackmcdade** [comment]
I'm not sure it's an improvement actually, it seems you commented out a couple lines and added a few new lines that are in English only. If you can sort those out, I would be happy to merge the PR. 😎

**Comment by v0ff4k** [comment]
ouch, i see,  some files are not changed.
yes i  oriented on variables based on english lang. cause in "ru" its too outdated(some vars are not used, some not in the right orders). ok, i''ll update my changes !

**Comment by v0ff4k** [comment]
It seems that I was the first to hurry up and did not check everything properly, I left (commented out) some lines of code for future checking and forgot about it. Now I rechecked all the files and code, and deleted unused lines.

**Comment by ebeauchamps** [comment]
Seems to me that at least one string is not translated, but that's perhaps on purpose?
`Toggle Sets`

**Comment by v0ff4k** [comment]
Thakn you, added translation, but done in next pull request.

**Pull request merged**
