### PR TITLE
Updating the repo with not so old DE and NL locales

### PR DESCRIPTION
**Pull request by ebeauchamps**
Also modified the Readme file to pinpoint the latest version available
per locale

### CODE REVIEW

**Comment by jackmcdade** [comment]
Nice!

**Comment by ebeauchamps** [comment]
my pleasure!!

**Comment by jackmcdade** [comment]
My apologies for this taking forever and an age to get switched over to v2 😊

**Comment by ebeauchamps** [comment]
I guess a "call for action" on Slack could make the difference in order to get new translators to work for Statamic. Statamic is apparently popular in Belgium, The Netherlands and Germany, so you need updated translations for Dutch and German.

**Pull request merged**
